# Site settings
title: Dharmatala
email: kenny.namgyal@gmail.com
description: A journal for householder practictioners of Karma Kagyu Tibetan Buddhism
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://dharmatala.net" # the base hostname & protocol for your site

twitter_username: kennynamgyal

# Build settings
markdown: kramdown
excerpt_separator: "<!--more-->"
permalink: pretty

exclude: ['Rakefile','Capfile','config','env.rb']

plugins:
    - jekyll-coffeescript
    
defaults:
    -
        scope:
            path: "" # an empty string here means all files in the project
            type: "posts" # previously `post` in Jekyll 2.2.
        values:
            comments: True

#twitter: // Add twitter key, secret, token and token secret
