# Site settings
title: Dharmatala
email: kenny.namgyal@gmail.com
description: A journal for householder practictioners of Karma Kagyu Tibetan Buddhism
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://dharmatala.net" # the base hostname & protocol for your site

twitter_username: kenny.namgyal

# Build settings
markdown: kramdown
excerpt_separator: "<!--more-->"
permalink: pretty

# defaults:
#   -
#     scope:
#       path: "" # an empty string here means all files in the project
#       type: "posts" # previously `post` in Jekyll 2.2.
#     values:
#       layout: "default"
#       author: "karma_tashi_namgyal"

